=begin
#Track & Trace Events

#Retrieve Track & Trace Events based on DCSA Interface standard v.2.2  This service provides visibility to Shipment, Equipment and Transport events for shipments booked with A.P. Moller-Maersk A/S using standards set by the Digital Container Shipping Association.\\ <https://dcsa.org/> 

The version of the OpenAPI document: 1.2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MaerskClient::DocumentReferencesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MaerskClient::DocumentReferencesInner do
  let(:instance) { MaerskClient::DocumentReferencesInner.new }

  describe 'test an instance of DocumentReferencesInner' do
    it 'should create an instance of DocumentReferencesInner' do
      expect(instance).to be_instance_of(MaerskClient::DocumentReferencesInner)
    end
  end
  describe 'test attribute "document_reference_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["BKG", "TRD"])
      # validator.allowable_values.each do |value|
      #   expect { instance.document_reference_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "document_reference_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
