=begin
#Track & Trace Events

#Retrieve Track & Trace Events based on DCSA Interface standard v.2.2  This service provides visibility to Shipment, Equipment and Transport events for shipments booked with A.P. Moller-Maersk A/S using standards set by the Digital Container Shipping Association.\\ <https://dcsa.org/> 

The version of the OpenAPI document: 1.2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MaerskClient::EventReferencesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MaerskClient::EventReferencesInner do
  let(:instance) { MaerskClient::EventReferencesInner.new }

  describe 'test an instance of EventReferencesInner' do
    it 'should create an instance of EventReferencesInner' do
      expect(instance).to be_instance_of(MaerskClient::EventReferencesInner)
    end
  end
  describe 'test attribute "reference_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["FF", "SI", "PO", "CR", "AAO", "EQ"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reference_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "reference_value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
