=begin
#Track & Trace Events

#Retrieve Track & Trace Events based on DCSA Interface standard v.2.2  This service provides visibility to Shipment, Equipment and Transport events for shipments booked with A.P. Moller-Maersk A/S using standards set by the Digital Container Shipping Association.\\ <https://dcsa.org/> 

The version of the OpenAPI document: 1.2.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.1

=end

# Common files
require 'maersk_client/api_client'
require 'maersk_client/api_error'
require 'maersk_client/version'
require 'maersk_client/configuration'

# Models
require 'maersk_client/models/address'
require 'maersk_client/models/api_error'
require 'maersk_client/models/api_validation_error'
require 'maersk_client/models/document_references_inner'
require 'maersk_client/models/equipment_event'
require 'maersk_client/models/event'
require 'maersk_client/models/event_references_inner'
require 'maersk_client/models/events'
require 'maersk_client/models/events_events_inner'
require 'maersk_client/models/location'
require 'maersk_client/models/seal'
require 'maersk_client/models/shipment_event'
require 'maersk_client/models/transport_call'
require 'maersk_client/models/transport_event'
require 'maersk_client/models/vessel'

# APIs
require 'maersk_client/api/events_api'

module MaerskClient
  class << self
    # Customize default settings for the SDK using block.
    #   MaerskClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
